apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
  name: {{ .Values.kafka.username }}
  namespace: {{ .Values.kafka.namespace }}
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: {{ .Values.kafka.username }}
          name: {{ .Values.kafka.username }}-creds
    type: scram-sha-512